"use strict";
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.resolve(__dirname, "..");
let pass = 0;
let fail = 0;
function check(condition, message) {
  if (condition) pass += 1;
  else { fail += 1; console.error(`FAIL: ${message}`); }
}

const context = {window:{}};
vm.createContext(context);
for (const file of ["course-core.js", "data-course.js"]) {
  vm.runInContext(fs.readFileSync(path.join(root, "assets", file), "utf8"), context, {filename:file});
}
const course = context.window.PyCourse;
const pages = ["index.html", "py-101.html", "py-201.html", "py-301.html", "py-401.html", "py-reference.html"];
const requiredDomains = ["Core", "Automation", "Backend", "Data", "ML", "AI"];
const requiredTracks = {Beginner:10, Intermediate:10, Advanced:11, Capstones:6, Reference:4};

check(course.title === "Python Learning Lab", "course title");
check(course.version === "1.0" && course.release === "October 2026", "visible release metadata");
check(course.author === "Namiranian, Babak", "exact author");
check(course.modules.length === 41, "41-module curriculum");
check(course.resources.length >= 30, "resource catalog breadth");
check(new Set(course.modules.map(module => module.id)).size === course.modules.length, "unique module IDs");

for (const [track, count] of Object.entries(requiredTracks)) {
  const modules = course.modules.filter(module => module.track === track);
  check(modules.length === count, `${track} module count`);
  for (const domain of requiredDomains) check(modules.some(module => module.domains.includes(domain)), `${track} exposes ${domain} path`);
}

const resourceIds = new Set(course.resources.map(resource => resource.id));
for (const module of course.modules) {
  check(/^PY-\d{3}$/.test(module.id), `${module.id} identifier`);
  check(module.summary.length >= 90, `${module.id} substantial summary`);
  check(module.outcomes.length >= 4, `${module.id} outcomes`);
  check(module.chapters.length === 4, `${module.id} four-part explanation`);
  check(module.chapters.every(chapter => chapter.title && chapter.text.length >= 2 && chapter.text.every(text => text.length >= 120)), `${module.id} substantial chapter content`);
  check(module.model?.steps?.length === 4, `${module.id} visual flow`);
  check(module.example?.language === "Python" && module.example.source.length >= 100, `${module.id} runnable Python example`);
  check(module.practice?.steps?.length >= 4 && module.practice.criteria.length >= 4 && module.practice.hints.length >= 3, `${module.id} guided practice`);
  check(module.diagnostic?.options?.length === 4 && Number.isInteger(module.diagnostic.answer), `${module.id} diagnostic`);
  check(module.checks.length === 3 && module.checks.every(item => item.options.length === 4 && item.why.length >= 50), `${module.id} retrieval checks`);
  check(module.project.length >= 90, `${module.id} transfer challenge`);
  check(module.domains.length >= 1 && module.domains.every(domain => requiredDomains.includes(domain)), `${module.id} valid domains`);
  check(module.resources.length >= 3 && module.resources.every(id => resourceIds.has(id)), `${module.id} valid references`);
  const lessonWords = module.chapters.flatMap(chapter => chapter.text).join(" ").split(/\s+/).length;
  check(lessonWords >= 300, `${module.id} lesson depth (${lessonWords} words)`);
}

for (const resource of course.resources) {
  check(/^https:\/\//.test(resource.url), `${resource.id} HTTPS URL`);
  check(resource.title && resource.provider && resource.kind && resource.bestFor && resource.scope && resource.access, `${resource.id} complete resource metadata`);
}
check(course.resources.some(resource => /Coursera/.test(resource.provider)), "Coursera resources included");
check(course.resources.some(resource => /YouTube/.test(resource.kind)), "YouTube resources included");
check(course.resources.some(resource => /Paid|Freemium/.test(resource.access)), "paid options clearly labeled");

for (const page of pages) {
  const html = fs.readFileSync(path.join(root, page), "utf8");
  check(/<meta name="author" content="Namiranian, Babak">/.test(html), `${page} exact author metadata`);
  check(/assets\/python-logo\.svg/.test(html), `${page} Python favicon`);
  check(/assets\/python-course\.css\?v=1\.0/.test(html), `${page} versioned CSS`);
  check(/assets\/course-core\.js\?v=1\.0/.test(html) && /assets\/data-course\.js\?v=1\.0/.test(html) && /assets\/python-course\.js\?v=1\.0/.test(html), `${page} ordered scripts`);
}

for (const file of fs.readdirSync(path.join(root, "assets"))) {
  const full = path.join(root, "assets", file);
  if (!fs.statSync(full).isFile()) continue;
  const text = fs.readFileSync(full, "utf8");
  check(!/JavaScript Learning Lab|JSCourse|Node\.js first|JS-\d{3}/.test(text), `${file} contains no inherited JavaScript branding`);
  check(!/Prepared by|Generated by|OpenAI|ChatGPT|Codex/i.test(text), `${file} contains no generator credit`);
}

console.log(`PASS ${pass} FAIL ${fail}`);
process.exitCode = fail ? 1 : 0;
