"use strict";
const fs=require("node:fs"),path=require("node:path"),http=require("node:http"),assert=require("node:assert/strict");
const {chromium}=require("playwright");
const SHARED="/Users/BNamira/code/Shared",SHOTS="/private/tmp/java-learning-lab-v1-screenshots";let passed=0,failed=0;
function check(name,condition,detail=""){try{assert.ok(condition,detail);passed++;}catch(error){failed++;console.error("FAIL",name,detail||error.message);}}
function server(){const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".svg":"image/svg+xml"};return http.createServer((request,response)=>{const pathname=decodeURIComponent(new URL(request.url,"http://local").pathname);let relative=pathname.replace(/^\/+/,"").replace(/^shared\/?/,"")||"index.html";let target=path.resolve(SHARED,relative);if(pathname.endsWith("/"))target=path.join(target,"index.html");if(!target.startsWith(SHARED+path.sep)){response.writeHead(403).end("Forbidden");return;}fs.readFile(target,(error,data)=>{if(error){response.writeHead(404).end("Not found");return;}response.writeHead(200,{"content-type":types[path.extname(target)]||"application/octet-stream","cache-control":"no-store"});response.end(data);});});}
async function noOverflow(page){return page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1);}
async function uniqueIds(page){return page.evaluate(()=>{const ids=[...document.querySelectorAll("[id]")].map(n=>n.id);return ids.length===new Set(ids).size;});}
async function namedControls(page){return page.evaluate(()=>[...document.querySelectorAll("a,button,input,textarea,select")].filter(n=>!n.hidden&&getComputedStyle(n).display!=="none").every(n=>Boolean(n.getAttribute("aria-label")||n.getAttribute("aria-labelledby")||n.labels?.length||n.textContent.trim()||n.querySelector("img[alt]"))));}
async function main(){
 fs.mkdirSync(SHOTS,{recursive:true});const site=server();await new Promise((resolve,reject)=>site.listen(0,"127.0.0.1",e=>e?reject(e):resolve()));const base=`http://127.0.0.1:${site.address().port}/shared/`;const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:["clipboard-read","clipboard-write"]});const page=await context.newPage(),errors=[];page.on("pageerror",e=>errors.push(String(e)));page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
 await page.goto(base+"ProgramLanguages/Java/",{waitUntil:"networkidle"});check("home paths",await page.locator(".path-card").count()===5);check("visible home",await page.locator(".home-button").isVisible());check("version",(await page.locator("body").innerText()).includes("V1.0 · October 2026"));check("favicon",await page.locator('link[rel="icon"]').getAttribute("href")==="assets/java-logo.svg");check("graphics",await page.locator(".hero-art svg").count()===1&&await page.locator(".path-art svg").count()===5);check("controls",await namedControls(page));check("IDs",await uniqueIds(page));check("overflow",await noOverflow(page));check("normalized home",await page.evaluate(()=>parseFloat(getComputedStyle(document.querySelector(".home-hero h1")).fontSize)<=58&&document.querySelector(".home-hero").getBoundingClientRect().height<=500));
 const resume=page.getByRole("link",{name:"Resume JV-001"});check("resume protected",await resume.evaluate(a=>a.target==="_blank"&&a.rel.includes("noopener")&&a.rel.includes("noreferrer")));const resumeEvent=page.waitForEvent("popup");await resume.click();const resumePage=await resumeEvent;await resumePage.waitForLoadState("networkidle");check("resume new tab",resumePage.url().endsWith("java-101.html#jv-001"));await resumePage.close();
 await page.getByRole("button",{name:"Resources"}).click();const resourceText=await page.locator("#resourceDirectory").innerText();check("resource breadth",await page.locator(".resource-card").count()>=25);check("Coursera",resourceText.includes("Coursera"));check("YouTube",resourceText.includes("YouTube"));check("official Java",resourceText.includes("Learn Java")&&resourceText.includes("Java Language Specification"));check("cost labels",resourceText.includes("Freemium/Paid")&&resourceText.includes("Version scope:"));await page.locator("#resourcesDialog .modal-close").click();
 const tracks={"java-101.html":8,"java-201.html":9,"java-301.html":8,"java-401.html":4,"java-reference.html":3};for(const [file,count]of Object.entries(tracks)){await page.goto(base+"ProgramLanguages/Java/"+file,{waitUntil:"networkidle"});check(`${file} module count`,await page.locator(".module-card").count()===count);check(`${file} protected new tabs`,await page.locator(".module-card").evaluateAll(cards=>cards.every(card=>card.target==="_blank"&&card.rel.includes("noopener")&&card.rel.includes("noreferrer"))));check(`${file} domain filter`,await page.locator(".domain-filter button").count()===7);check(`${file} graphics`,await page.locator(".module-art svg").count()===count);check(`${file} overflow`,await noOverflow(page));}
 await page.goto(base+"ProgramLanguages/Java/java-201.html",{waitUntil:"networkidle"});await page.locator('[data-domain="Tooling"]').click();check("domain filter",await page.locator(".module-card:visible").count()<9&&await page.locator(".module-card:visible").count()>0);await page.locator("#courseSearch").fill("genercs");check("typo search",await page.locator('[data-nav-id="JV-009"]').isVisible());
 await page.goto(base+"ProgramLanguages/Java/java-101.html",{waitUntil:"networkidle"});const popupEvent=page.waitForEvent("popup");await page.locator(".module-card").first().click();const lesson=await popupEvent;await lesson.waitForLoadState("networkidle");check("lesson new tab",lesson.url().endsWith("java-101.html#jv-001"));check("four deep chapters",await lesson.locator(".lesson-chapter").count()===4&&await lesson.locator(".lesson-chapter").evaluateAll(chapters=>chapters.every(chapter=>chapter.querySelectorAll(":scope > div > p").length>=2)));check("domain tags",await lesson.locator(".lesson-hero .domain-tags span").count()===5);check("visual flow",await lesson.locator(".model-step").count()===4);check("Java highlighting",await lesson.locator(".tok-keyword").count()>0);check("practice and checks",await lesson.locator(".practice-section").count()===1&&await lesson.locator(".hints details").count()===3&&await lesson.locator("[data-diagnostic]").count()===1&&await lesson.locator("[data-quiz] fieldset").count()===3);check("Top control",await lesson.locator("[data-to-top]").count()===1);check("lesson controls",await namedControls(lesson));check("lesson IDs",await uniqueIds(lesson));check("lesson overflow",await noOverflow(lesson));check("starts incomplete",(await lesson.locator(".completion-panel").innerText()).includes("Mark module complete"));await lesson.locator('[data-complete="JV-001"]').click();check("completion persists",await lesson.evaluate(()=>JSON.parse(localStorage.getItem("java-learning-lab-v1")).done["JV-001"]===true));check("progress",(await lesson.locator("#progressText").innerText())==="1 of 32");
 const quiz=lesson.locator('[data-quiz="JV-001"]');for(const [i,value]of [[0,"0"],[1,"0"],[2,"1"]])await quiz.locator(`input[name="q-${i}"][value="${value}"]`).check();await quiz.getByRole("button",{name:"Score and explain"}).click();check("quiz",(await quiz.locator(".quiz-summary").innerText()).includes("3 of 3"));const copy=lesson.locator("button[data-copy]").first(),code=await lesson.locator(`#${await copy.getAttribute("data-copy")}`).textContent(),theme=await lesson.evaluate(()=>document.documentElement.dataset.theme);await copy.click();await lesson.waitForFunction(()=>document.querySelector("button[data-copy]")?.textContent==="Copied");check("copy exact",await lesson.evaluate(()=>navigator.clipboard.readText())===code);check("copy no theme change",await lesson.evaluate(()=>document.documentElement.dataset.theme)===theme);await lesson.locator("button[data-theme]").click();check("theme persists",await lesson.evaluate(()=>document.documentElement.dataset.theme==="dark"&&JSON.parse(localStorage.getItem("java-learning-lab-v1")).theme==="dark"));await lesson.screenshot({path:path.join(SHOTS,"jv-001-desktop.png"),fullPage:true});await lesson.close();
 for(const width of[1024,768,390]){const mobile=await browser.newContext({viewport:{width,height:width===390?844:900}}),p=await mobile.newPage(),localErrors=[];p.on("pageerror",e=>localErrors.push(String(e)));await p.goto(base+"ProgramLanguages/Java/",{waitUntil:"networkidle"});check(`${width} home overflow`,await noOverflow(p));check(`${width} all paths`,await p.locator(".path-card").count()===5);await p.goto(base+"ProgramLanguages/Java/java-101.html",{waitUntil:"networkidle"});check(`${width} map overflow`,await noOverflow(p));if(width<=768){await p.getByRole("button",{name:"Modules"}).click();check(`${width} drawer`,await p.locator(".course-nav").isVisible());}await p.goto(base+"ProgramLanguages/Java/java-101.html#jv-002",{waitUntil:"networkidle"});check(`${width} lesson overflow`,await noOverflow(p));check(`${width} Home visible`,await p.locator(".home-button").isVisible());check(`${width} runtime`,localErrors.length===0,localErrors.join(" | "));if(width===390)await p.screenshot({path:path.join(SHOTS,"jv-002-mobile.png"),fullPage:true});await mobile.close();}
 check("runtime errors",errors.length===0,errors.join(" | "));await context.close();await browser.close();await new Promise(resolve=>site.close(resolve));console.log(`RESULT ${passed} checks passed; ${failed} failures`);console.log("SCREENSHOTS",SHOTS);if(failed)process.exitCode=1;
}
main().catch(error=>{console.error(error);process.exit(1);});
